### PR TITLE
Fix ng-option filter expressions

### LINKED ISSUE #5: Using piped filters
Is something like <code>ng-options="option.id as option.name for option in options | filter1 "</code> (please not the | sign) possible?

### PR DESCRIPTION
**Pull request by stgeorge**
Fixes #5

### CODE REVIEW

**Comment by Chris-Gillis** [comment]
Nice fix!

Would you mind adding a test for this scenario?

Edit: I just noticed you said you are unable to test. Is there something I can do to help you with that?

**Comment by stgeorge** [comment]
I don't have a nodejs setup or much time to look into setting it up at the moment unfortunately - I'll have to leave it up to someone else to make a functional test. My apologies.

**Comment by EvanOxfeld** [comment]
@stgeorge I appreciate your help getting filter expressions to work!

Please don't worry about tests -- fortunately you got me most of the way (ok, all of the way :smile:), and this scenario is pretty straightforward to write tests for.

**Comment by EvanOxfeld** [comment]
I thought I discovered an issue with this change, but instead there was a bug in the version of selectize I usually test against that must have been fixed between 0.9.0 and 0.11.0. When I have a chance to work on this again, I'll determine the new minimum version of selectize and write a couple tests.

For now, I welcome comments on the plunk I've been testing with: http://plnkr.co/edit/mO7ssw?p=preview

**Comment by EvanOxfeld** [comment]
Merged and published as version `1.4.0`. I added a few tests as well as multiselect ngoption filter expression support.

Thanks again for the fix, @stgeorge!

**Comment by stgeorge** [comment]
Thanks @EvanOxfeld and keep up the good work on this library!

**Pull request merged**
